[[protocols]]
name = "combo_direct_ch1"
protocol = "pulse_distance"
margin = 200
header_pulse = 158
header_space = 1026
bit_pulse = 158
bit_0_space = 263
bit_1_space = 553
trailer_pulse = 158
bits = 16

[protocols.information]
brand = "LEGO"
name = "LEGO_combo_direct_ch1"
contributed_by = "Rique_Checchi"
devices_controlled = "8884_Power_Functions_IR_Receiver"

[protocols.scancodes]
0x010E = "FLT_FLT_0"
0x011F = "FW7_FLT_0"
0x012C = "RV7_FLT_0"
0x013D = "BRK_FLT_0"
0x014A = "FLT_FW7_0"
0x015B = "FW7_FW7_0"
0x0168 = "RV7_FW7_0"
0x0179 = "BRK_FW7_0"
0x0186 = "FLT_RV7_0"
0x0197 = "FW7_RV7_0"
0x01A4 = "RV7_RV7_0"
0x01B5 = "BRK_RV7_0"
0x01C2 = "FLT_BRK_0"
0x01D3 = "FW7_BRK_0"
0x01E0 = "RV7_BRK_0"
0x01F1 = "BRK_BRK_0"
0x8106 = "FLT_FLT_1"
0x8117 = "FW7_FLT_1"
0x8124 = "RV7_FLT_1"
0x8135 = "BRK_FLT_1"
0x8142 = "FLT_FW7_1"
0x8153 = "FW7_FW7_1"
0x8160 = "RV7_FW7_1"
0x8171 = "BRK_FW7_1"
0x818E = "FLT_RV7_1"
0x819F = "FW7_RV7_1"
0x81AC = "RV7_RV7_1"
0x81BD = "BRK_RV7_1"
0x81CA = "FLT_BRK_1"
0x81DB = "FW7_BRK_1"
0x81E8 = "RV7_BRK_1"
0x81F9 = "BRK_BRK_1"