[[protocols]]
name = "extended_ch1"
protocol = "pulse_distance"
margin = 200
header_pulse = 158
header_space = 1026
bit_pulse = 158
bit_0_space = 263
bit_1_space = 553
trailer_pulse = 158
bits = 16

[protocols.information]
brand = "LEGO"
name = "LEGO_combo_direct_ch1"
contributed_by = "Rique_Checchi"
devices_controlled = "8884_Power_Functions_IR_Receiver"

[protocols.scancodes]
0x000F = "A_BRK_00"
0x001E = "A_INC_00"
0x002D = "A_DEC_00"
0x004B = "B_TOG_00"
0x0069 = "ADD_TOG_00"
0x0078 = "TOG_AGN_00"
0x0087 = "RSVD_00"
0x8007 = "A_BRK_10"
0x8016 = "A_INC_10"
0x8025 = "A_DEC_10"
0x8043 = "B_TOG_10"
0x8061 = "ADD_TOG_10"
0x8070 = "TOG_AGN_10"
0x808F = "RSVD_10"
0x0807 = "A_BRK_01"
0x0816 = "A_INC_01"
0x0825 = "A_DEC_01"
0x0843 = "B_TOG_01"
0x0861 = "ADD_TOG_01"
0x0870 = "TOG_AGN_01"
0x088F = "RSVD_01"
0x880F = "A_BRK_11"
0x881E = "A_INC_11"
0x882D = "A_DEC_11"
0x884B = "B_TOG_11"
0x8869 = "ADD_TOG_11"
0x8878 = "TOG_AGN_11"
0x8887 = "RSVD_11"