[[protocols]]
name = "single_other_ch1"
protocol = "pulse_distance"
margin = 200
header_pulse = 158
header_space = 1026
bit_pulse = 158
bit_0_space = 263
bit_1_space = 553
trailer_pulse = 158
bits = 16

[protocols.information]
brand = "LEGO"
name = "LEGO_combo_direct_ch1"
contributed_by = "Rique_Checchi"
devices_controlled = "8884_Power_Functions_IR_Receiver"

[protocols.scancodes]
0x0609 = "A_TOG_0000_0"
0x0618 = "A_TOG_0001_0"
0x062B = "A_INC_NUM_0"
0x063A = "A_DEC_NUM_0"
0x064D = "A_INC_PWM_0"
0x065C = "A_DEC_PWM_0"
0x066F = "A_FUL_FWD_0"
0x067E = "A_FUL_REV_0"
0x0681 = "A_TOG_1000_0"
0x0690 = "A_CLR_C1_0"
0x06A3 = "A_SET_C1_0"
0x06B2 = "A_TOG_C1_0"
0x06C5 = "A_CLR_C2_0"
0x06D4 = "A_SET_C2_0"
0x06E7 = "A_TOG_C2_0"
0x06F6 = "A_TOG_1111_0"
0x0708 = "B_TOG_0000_0"
0x0719 = "B_TOG_0001_0"
0x072A = "B_INC_NUM_0"
0x073B = "B_DEC_NUM_0"
0x074C = "B_INC_PWM_0"
0x075D = "B_DEC_PWM_0"
0x076E = "B_FUL_FWD_0"
0x077F = "B_FUL_REV_0"
0x0780 = "B_TOG_1000_0"
0x0791 = "B_CLR_C1_0"
0x07A2 = "B_SET_C1_0"
0x07B3 = "B_TOG_C1_0"
0x07C4 = "B_CLR_C2_0"
0x07D5 = "B_SET_C2_0"
0x07E6 = "B_TOG_C2_0"
0x07F7 = "B_TOG_1111_0"
0x8601 = "A_TOG_0000_1"
0x8610 = "A_TOG_0001_1"
0x8623 = "A_INC_NUM_1"
0x8632 = "A_DEC_NUM_1"
0x8645 = "A_INC_PWM_1"
0x8654 = "A_DEC_PWM_1"
0x8667 = "A_FUL_FWD_1"
0x8676 = "A_FUL_REV_1"
0x8689 = "A_TOG_1000_1"
0x8698 = "A_CLR_C1_1"
0x86AB = "A_SET_C1_1"
0x86BA = "A_TOG_C1_1"
0x86CD = "A_CLR_C2_1"
0x86DC = "A_SET_C2_1"
0x86EF = "A_TOG_C2_1"
0x86FE = "A_TOG_1111_1"
0x8700 = "B_TOG_0000_1"
0x8711 = "B_TOG_0001_1"
0x8722 = "B_INC_NUM_1"
0x8733 = "B_DEC_NUM_1"
0x8744 = "B_INC_PWM_1"
0x8755 = "B_DEC_PWM_1"
0x8766 = "B_FUL_FWD_1"
0x8777 = "B_FUL_REV_1"
0x8788 = "B_TOG_1000_1"
0x8799 = "B_CLR_C1_1"
0x87AA = "B_SET_C1_1"
0x87BB = "B_TOG_C1_1"
0x87CC = "B_CLR_C2_1"
0x87DD = "B_SET_C2_1"
0x87EE = "B_TOG_C2_1"
0x87FF = "B_TOG_1111_1"