[[protocols]]
name = "single_other_ch1"
protocol = "pulse_distance"
margin = 200
header_pulse = 158
header_space = 1026
bit_pulse = 158
bit_0_space = 263
bit_1_space = 553
trailer_pulse = 158
bits = 16

[protocols.scancodes]
0x0609 = "R_TOG_0000"
0x0618 = "R_TOG_DIR"
0x062B = "R_INC_NUM"
0x063A = "R_DEC_NUM"
0x064D = "R_INC_PWM"
0x065C = "R_DEC_PWM"
0x066F = "R_FUL_FWD"
0x067E = "R_FUL_BCK"
0x0681 = "R_TOG_1000"
0x0690 = "R_CLR_C1"
0x06A3 = "R_SET_C1"
0x06B2 = "R_TOG_C1"
0x0690 = "R_CLR_C2"
0x06A3 = "R_SET_C2"
0x06B2 = "R_TOG_C2"
0x06F6 = "R_TOG_1111"
0x0708 = "B_TOG_0000"
0x0719 = "B_TOG_DIR"
0x072A = "B_INC_NUM"
0x073B = "B_DEC_NUM"
0x074C = "B_INC_PWM"
0x075D = "B_DEC_PWM"
0x076E = "B_FUL_FWD"
0x077F = "B_FUL_BCK"
0x0780 = "B_TOG_1000"
0x0791 = "B_CLR_C1"
0x07A2 = "B_SET_C1"
0x07B3 = "B_TOG_C1"
0x0791 = "B_CLR_C2"
0x07A2 = "B_SET_C2"
0x07B3 = "B_TOG_C2"
0x07F7 = "B_TOG_1111"