[[protocols]]
name = "single_pwm_ch1"
protocol = "pulse_distance"
margin = 200
header_pulse = 158
header_space = 1026
bit_pulse = 158
bit_0_space = 263
bit_1_space = 553
trailer_pulse = 158
bits = 16

[protocols.information]
brand = "LEGO"
name = "LEGO_combo_direct_ch1"
contributed_by = "Rique_Checchi"
devices_controlled = "8884_Power_Functions_IR_Receiver"

[protocols.scancodes]
0x040B = "R_FLT"
0x041A = "R_FW1"
0x0429 = "R_FW2"
0x0438 = "R_FW3"
0x044F = "R_FW4"
0x045E = "R_FW5"
0x046D = "R_FW6"
0x047C = "R_FW7"
0x0483 = "R_BRK"
0x0492 = "R_RV7"
0x04A1 = "R_RV6"
0x04B0 = "R_RV5"
0x04C7 = "R_RV4"
0x04D6 = "R_RV3"
0x04E5 = "R_RV2"
0x04F4 = "R_RV1"
0x050A = "B_FLT"
0x051B = "B_FW1"
0x0528 = "B_FW2"
0x0539 = "B_FW3"
0x054E = "B_FW4"
0x055F = "B_FW5"
0x056C = "B_FW6"
0x057D = "B_FW7"
0x0582 = "B_BRK"
0x0593 = "B_RV7"
0x05A0 = "B_RV6"
0x05B1 = "B_RV5"
0x05C6 = "B_RV4"
0x05D7 = "B_RV3"
0x05E4 = "B_RV2"
0x05F5 = "B_RV1"